# Étape 1 : Installation des dépendances et exécution des tests
FROM node:18-slim AS build-stage
WORKDIR /app

# Copie des fichiers de configuration de package
COPY package.json ./

# Installation des outils de test (eslint, htmlhint, jest)
RUN npm install

# Copie du reste du code source
COPY . .

# Lancement des tests de qualité (Linting) et tests unitaires
RUN npm run lint
RUN npm run test

# Étape 2 : Création de l'image de production si les tests réussissent
FROM nginx:alpine
COPY --from=build-stage /app /usr/share/nginx/html
EXPOSE 80